page/urls.py
from django.urls import path
from . views import AboutPageView, ContactPageView, ConfigPageView, AccountDelete, CancelPageView

app_name = 'page'

urlpatterns = [
    path('sobre/', AboutPageView.as_view(), name='about'),
    path('contato/', ContactPageView.as_view(), name='contact'),
    path('configuracao/<int:pk>/', ConfigPageView.as_view(), name='config'),
    path('deletar_conta/<int:pk>/', AccountDelete.as_view(), name='account_delete'),
    path('cancelado/', CancelPageView.as_view(), name='cancel'),
]

products/urls.py
from django.urls import path
from . views import HomePageView, ProductsPageView, ProductDetailPageView, ProductsCategoryView,  SearchResults

app_name = 'products'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('produtos/', ProductsPageView.as_view(), name='products'),
    path('produtos/<slug:slug>/', ProductDetailPageView.as_view(), name='product_detail'),
    path('produtos/categoria/<slug:slug>/', ProductsCategoryView.as_view(), name='filter_products'),
    path('resultados/', SearchResults.as_view(), name='search_results'),
]

shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'cart' 

urlpatterns = [
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart-detail/', views.cart_detail, name='cart_detail'),
    path('item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart_clear/', views.cart_clear, name='cart_clear'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from payments.views import CreateCheckoutSessionView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('pagina/', include('page.urls')),
    path('cart/', include('shopping_cart.urls')),
    path('accounts/', include('allauth.urls')),
    path('create/', include('orders.urls')),
    path('create-checkout-session/<int:id>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tag %}

{% block title %}Meu Carrinho{% endblock %}

{% block content %}
<main>
  {% if request.session.cart.items %}
  <div class="cart-card">
    <div class="row">
      <div class="col-md-8 cart">
        <div class="cart-title">
          <div class="row">
            <div class="col"><h4><b>Carrinho de compras</b></h4></div>
            <div class="col align-self-center text-right">{{ request.session.cart|length }} items</div>
          </div>
        </div>    

				{% for key, value in request.session.cart.items %}
					<div class="row mt-3 border-bottom">
						<div class="row cart-main align-items-center">
              <a href="" class="col-2"><img class="img-fluid" src="{{ value.image }}"></a>
							<div class="col">
								<a href="" class="row">{{ value.name|truncatechars:20 }}</a>
							</div>
							<div class="col">
                <a href="{% url 'cart:item_decrement' value.product_id %}">-</a><a href="" class="border">{{ value.quantity }}</a><a href="{% url 'cart:item_increment' value.product_id %}">+</a>
							</div>
              <div class="col"><a href="">R$ {{ value.price }}</a> <a href="{% url 'cart:item_clear' value.product_id %}">&#10005;</a></div>
						</div>
					</div>
				{% endfor %}

        <div class="back-to-shop"><a href="{% url 'products:products' %}">&leftarrow;<span>Voltar a loja</span></a></div>
      </div>
      <div class="col-md-4 cart-summary">
        <div><h5><b>{{user.username}}</b></h5></div>
        <hr>

        {% if user.cpf %}
        <form action="{% url 'create-checkout-session' user.id %}" method="POST">
        {% else %}
        <form action="{% url 'page:config' user.id %}">
        {% endif %}
        {% csrf_token %}
        <div class="row">
          <div class="col mb-5">TOTAL </div>
            {{ cart_total_amount }}0
          <div class="col text-right"></div>
        </div>
        <div class="col-12"><a class="btn btn-danger" href="{% url 'cart:cart_clear' %}">Limpar Carrinho</a></div>
        <button class="btn buy-btn">COMPRAR</button>
        </form>
      </div>
    </div>
  </div>
  {% else %}
  <div class="container">
    <div class="cart-empty">
      <h4>Carrinho Vazio</h4>
      <img src="{% static 'imgs/cart.png' %}" alt="">
    </div>
  </div>
  {% endif %}
</main>

{% include 'footer.html' %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>
{% endblock content %}