page/urls.py
from django.urls import path
from . views import AboutPageView, ContactPageView, ConfigPageView, AccountDelete, CancelPageView

app_name = 'page'

urlpatterns = [
    path('sobre/', AboutPageView.as_view(), name='about'),
    path('contato/', ContactPageView.as_view(), name='contact'),
    path('configuracao/<int:pk>/', ConfigPageView.as_view(), name='config'),
    path('deletar_conta/<int:pk>/', AccountDelete.as_view(), name='account_delete'),
    path('cancelado/', CancelPageView.as_view(), name='cancel'),
]

products/urls.py
from django.urls import path
from . views import HomePageView, ProductsPageView, ProductDetailPageView, ProductsCategoryView,  SearchResults

app_name = 'products'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('produtos/', ProductsPageView.as_view(), name='products'),
    path('produtos/<slug:slug>/', ProductDetailPageView.as_view(), name='product_detail'),
    path('produtos/categoria/<slug:slug>/', ProductsCategoryView.as_view(), name='filter_products'),
    path('resultados/', SearchResults.as_view(), name='search_results'),
]

shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'cart' 

urlpatterns = [
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart-detail/', views.cart_detail, name='cart_detail'),
    path('item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart_clear/', views.cart_clear, name='cart_clear'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from payments.views import CreateCheckoutSessionView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('pagina/', include('page.urls')),
    path('cart/', include('shopping_cart.urls')),
    path('accounts/', include('allauth.urls')),
    path('create/', include('orders.urls')),
    path('create-checkout-session/<int:id>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sobre{% endblock title %}

{% block content %}
<main>
  <div class="top-banner">
      <h2>SOBRE</h2>
  </div>
  <div class="about-body container justify-content-center">
    <div class="row align-items-center">
      {% for field in about %}
      <div class="col-sm-12 col-md-6 col-lg-4">
        <img src="{{ field.image.url }}" alt="" class="img-fluid d-block m-auto">
      </div>
      <div class="col-sm-12 col-md-6 col-lg-8">
        <h1>Nossa História</h1>
        <p>{{ field.about }}</p>
      </div>
      {% endfor %}
    </div>
  </div>
</main>
{% include 'footer.html' %}
{% endblock content %}

templates/base.html
{% load static %}
{% load cart_tag %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="rating" content="general">
    <meta name="author" content="Gabriel Santana">
    <meta name="description" content="...">
    <meta name="keywords" content="...">
    <meta name="copyright" content="© Gabriel Santana">
    <title>{% block title %}Thunder Variedades{% endblock title %}</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Poppins&display=swap" rel="stylesheet"> 
  </head>
  <body>
    <header id="mobile-header">
      <!-- TopBar -->
      <section class="topbar">
        <span><a href="/">Thunder Store</a></span>

        <div class="topbar-icons">
          {% if user.is_authenticated %}
            {% if user.procfile_photo %}
            <a class="topbar-procfile-image" href="{% url 'page:config' user.id %}"><img src="{{user.procfile_photo.url}}" alt=""></a>
            {% else %}
              <a href="{% url 'page:config' user.id %}"><i class="bi bi-person-circle"></i></a>
            {% endif %}

          {% else %}
            <a href="{% url 'account_login' %}"><i class="bi bi-person-circle"></i></a>
          {% endif %}
          <a href="{% url 'cart:cart_detail' %}"><i class="bi bi-bag"></i><span class="badge bg-secondary">{{ request.session.cart|length }}</span></a>

          <input id="chk" type="checkbox">
          <label for="chk">
            <div onclick='dropdown()' class="hamburger-div">
              <div><span class="hamburger-icon"></span></div>
            </div>
          </label>
        </div>
      </section>

      <!-- Dropdown -->
      <section class="dropdown">
        <div class="dropdown-top">
          <form action="{% url 'products:search_results' %}" method="get">
            <input required="required" name="q" placeholder="  Buscar" class="search" type="search"><button class="btn btn-secundary"><i class="bi bi-search"></i></button>
          </form>

          <div class="translateAndtheme">
            <div class="btn-group" role="group">
                <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Traduzir
                </button>
                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <a class="dropdown-item" href="#">Inglês</a>
                <a class="dropdown-item" href="#">Português</a>
                </div>
              </div>
            <div class="theme">
              <input type="checkbox" id="ThemeChk">
              <label for="ThemeChk">
                <li onclick=theme() class="bi bi-moon-stars-fill moon"></li>
              </label>
            </div>
          </div>

          <div class="social-midia">
            <hr>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href="{% url 'page:contact' %}"><i class="bi bi-envelope"></i></a>
            <a href=""><i class="bi bi-whatsapp"></i></a>
            <a href=""><i class="bi bi-telegram"></i></a>
          </div>
        </div>

        <nav>
          <ul>
            <li><a href="{% url 'products:home' %}">Início</a></li>
            <li><a href="{% url 'products:products' %}">Loja</a></li>
            <li><a href="{% url 'page:about' %}">Sobre</a></li>
            <li><a href="{% url 'products:home' %}#featured-products">Destaques de Produtos</a></li>
            <li><a href="{% url 'page:contact' %}">Contato</a></li>
            <li><a href="{% url 'products:home' %}">Blog</a></li>
          </ul>
        </nav>
      </section>
    </header>

    <!-- Desktop Header -->
    <header id="all-desktop-header">
      <div class="desktop-header-top">
        <div class="topbar-icons">
          <a href=""><i class="bi bi-instagram"></i></a>
          <a href=""><i class="bi bi-facebook"></i></a>
          <a href="{% url 'page:contact' %}"><i class="bi bi-envelope"></i></a>
          <a href=""><i class="bi bi-whatsapp"></i></a>
          <a href=""><i class="bi bi-telegram"></i></a>
        </div>
        
        <form action="{% url 'products:search_results' %}" method="get">
            <input required="required" name="q" placeholder="  Buscar" class="search" type="search"><button class="btn btn-secundary"><i class="bi bi-search"></i></button>
        </form>

        <div class="translateAndtheme">
          <div class="theme">
            <input type="checkbox" id="ThemeChk">
            <label for="ThemeChk">
              <li onclick=theme() class="bi bi-moon-stars-fill moon"></li>
            </label>
          </div>
          <div class="btn-group" role="group">
              <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Traduzir
              </button>
              <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <a class="dropdown-item" href="#">Inglês</a>
                <a class="dropdown-item" href="#">Português</a>
              </div>
            </div>
        </div>

      </div>

      <div class="desktop-header">
        <span><a href="/">Thunder Store</a></span>
        <nav>
          <ul class="d-flex list-unstyled">
            <li><a href="{% url 'products:home' %}">Início</a></li>
            <li><a href="{% url 'products:products' %}">Loja</a></li>
            <li><a href="{% url 'page:about' %}">Sobre</a></li>
            <li><a href="{% url 'products:home' %}#featured-products">Destaques de Produtos</a></li>
            <li><a href="{% url 'page:contact' %}">Contato</a></li>
            <li><a href="{% url 'products:home' %}">Blog</a></li>
          </ul>
        </nav>

        <div>
          {% if user.is_authenticated %}
            {% if user.procfile_photo %}
            <a class="topbar-procfile-image" href="{% url 'page:config' user.id %}"><img src="{{user.procfile_photo.url}}" alt=""></a>
            {% else %}
              <a href="{% url 'page:config' user.id %}"><i class="bi bi-person-circle"></i></a>
            {% endif %}

          {% else %}
            <a href="{% url 'account_login' %}"><i class="bi bi-person-circle"></i></a>
          {% endif %}
          <a href="{% url 'cart:cart_detail' %}"><i class="bi bi-bag"></i><span class="badge bg-secondary">{{ request.session.cart|length }}</span></a>
        </div>
      </div>
    </header>

    {% block content %}
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

templates/cancel.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cancelado{% endblock title %}

{% block content %}
<main>
  <div class="success-page">
    <div>
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
      <h1>Cancelado</h1>
      <p>Seu pedido foi cancelado com sucesso!</p>
      <a href="{% url 'products:home' %}">Retornar</a>
    </div>
  </div>
</main>
{% endblock content %}

templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Produtos{% endblock %}

{% block content %}
<main>
  <div class="top-banner">
    <h2>{{ title }}</h2>
  </div>

  <div class="container my-5">
    <div class="row">
      <div class="col-4 col-md-3">
        <ul class="list-group mb-3 mb-lg-0">
          <a class="text-decoration-none list-group-item list-group-item-light" href="{% url 'products:products' %}">
            Todos os produtos
          </a>

          {% for category in categories %}
          <a class="text-decoration-none list-group-item list-group-item-light" href="{% url 'products:filter_products' category.name %}">{{ category.slug }}</a>
          {% endfor %}
        </ul>
      </div>

      <div class="col-8 col-md-9">
        <div class="row">
          {% for merchandise in products %}
          <div class="col-sm-12 col-md-6 col-lg-4 mb-4">
            <div class="card h-100">
              <a href="{% url 'products:product_detail' merchandise.slug %}">
                <img class="card-img-top" src="{{ merchandise.image.url }}" alt="">
              </a>

              <div class="card-body d-flex flex-column justify-content-between">
                <a class="text-decoration-none text-dark" href="{% url 'products:product_detail' merchandise.slug %}">
                  <h5 class="card-title">{{ merchandise.name }}</h5>
                </a>
                <a class="text-decoration-none text-dark" href="{% url 'products:product_detail' merchandise.slug %}">
                  <p class="card-text font-weight-bold">{{ merchandise.price }}</p>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}

          {% if is_paginated %}
            {% include 'pagination.html' with page=page_obj %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>

{% include 'footer.html' %}
{% endblock content %}

templates/config.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Configuração{% endblock title %}

{% block content %}
<div class="container d-flex mt-5  mb-5 justify-content-center">
  <form enctype="multipart/form-data" class="config-form" method="POST">
    {% csrf_token %}
    <div class="row g-3">
      <div class="col-12 procfile-config-image mb-4">
        {% if user.procfile_photo %}
        <a href="{{user.procfile_photo.url}}"><img id="img" src="{{user.procfile_photo.url}}" alt=""></a>
        {% else %}
        <img src="{% static 'imgs/fundo.jpg' %}" id="img" alt="">
        {% endif %}
        {{form.procfile_photo}}
      </div>
      <div class="col-12">
        {% if form.errors %}
          <p>{{ form.errors }}</p> 
          <hr>
        {% endif %}

        <label for="cpf" class="form-label">CPF*</label>
        {{form.cpf}}
      </div>
      <div class="col-12">
        <label for="name" class="form-label">Nome Completo*</label>
        {{form.username}}
      </div>
      <div class="col-12">
        <label for="email" class="form-label">Email*</label>
        {{form.email}}
      </div>
      <div class="col-4">
        <label for="cep" class="form-label">CEP*</label>
        {{form.cep}}
      </div>
      <div class="col-4">
        <label for="state" class="form-label">Estado*</label>
        {{form.state}}
      </div>
      <div class="col-4">
        <label for="city" class="form-label">Cidade*</label>
        {{form.city}}
      </div>
      <div class="col-6">
        <label for="address" class="form-label">Endereço*</label>
        {{form.address}}
      </div>
      <div class="col-6">
        <label for="district" class="form-label">Bairro*</label>
        {{form.district}}
      </div>
      <div class="col-6">
        <label for="number" class="form-label">Número*</label>
        {{form.number}}
      </div>
      <div class="col-6">
        <label for="complement" class="form-label">Complemento</label>
        {{form.complement}}
      </div>
      <div class="col-12">
        <input type="submit" value="Enviar" class="btn btn-success form-control">
      </div>
      <div class="col-sm-12">
        <a href=""  class="btn btn-secondary form-control">Mudar Senha</a>
      </div>
      <div class="col-sm-12">
        <a href="{% url 'account_logout' %}" class="btn btn-danger form-control">Sair</a>
      </div>
      <div class="col-sm-12">
        <a href="{% url 'page:account_delete' user.id %}" class="btn btn-danger form-control">Deletar Conta</a>
      </div>
    </div>
    <div class="m-4 back"><a href="{% url 'products:home' %}">Voltar</a></div>
  </form>
</div>

<script>
  var chk = window.document.getElementById('id_procfile_photo')
  chk.addEventListener('change', change_photo)
  function change_photo(){
    var img = window.document.getElementById('img')
    img.src = URL.createObjectURL(event.target.files[0]);
  }
</script>
{% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contato{% endblock title %}

{% block content %}
<main>
  <div class="top-banner">
      <h2>CONTATO</h2>
  </div>
  <div class="contact-body container d-flex justify-content-center">
    <div class="row align-items-center">
      <div class="col-sm-12 col-md-6 col-lg-4">
        <iframe class="d-block m-auto" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3957.9303532461595!2d-35.88749972406382!3d-7.248767392757745!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7ac1e77ac052899%3A0x634fb821becf5ed8!2sR.%20S%C3%A3o%20Judas%20Tadeu%20-%20Catol%C3%A9%2C%20Campina%20Grande%20-%20PB%2C%2058410-547!5e0!3m2!1spt-BR!2sbr!4v1669844555745!5m2!1spt-BR!2sbr" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
      <div class="col-sm-12 col-md-6 col-lg-8">
        <h1>Envie sua mensagem</h1>
        <form action="{% url 'page:contact' %}" method="POST">
          {% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-12 col-lg-6">
              <input type="text" placeholder="Nome" required="required" class="form-control" name="name" >
            </div>
            <div class="col-sm-12 col-lg-6">
              <input type="email" placeholder="E-mail" required="required" class="form-control" name="email" >
            </div>
            <div class="col-sm-12">
              <input type="text" placeholder="Assunto" required="required" class="form-control" name="subject" >
            </div>
            <div class="col-sm-12">
              <textarea placeholder="Sua mensagem" cols="30" rows="10" required="required" class="form-control" name="message" ></textarea>
            </div>
            <input type="submit" value="Enviar" class="btn btn-success">
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

{% include 'footer.html' %}
{% endblock content %}

templates/delete.html
{% extends 'base.html' %}

{% block titulo %}Deletar Conta{% endblock %}

{% block content %}

<main>
  <div class="exit-sys">
    <h2>Tem certeza que deseja deletar sua conta?</h2>
    <div>
      <form method='POST'>
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Deletar">
      </form>
      <a href="{% url 'page:config' user.id  %}">Cancelar</a>
    </div>
  </div>
</main>

{% endblock%}

templates/footer.html
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-lg-3">
        <h5>Entrar em Contato</h5>
        <p>Alguma dúvida? Fale conosco pelas formas de contato disponíveis abaixo. Em menos de 24 horas lhe retornaremos.</p>
        <ul class="social-midia list-unstyled d-flex">
          <li><a href=""><i class="bi bi-instagram"></i></a></li>
          <li><a href=""><i class="bi bi-facebook"></i></a></li>
          <li><a href="{% url 'page:contact' %}"><i class="bi bi-envelope"></i></a></li>
          <li><a href=""><i class="bi bi-whatsapp"></i></a></li>
          <li><a href=""><i class="bi bi-telegram"></i></a></li>
        </ul>
      </div>

      <div class="col-sm-12 col-lg-3">
        <h5>CATEGORIES</h5>
        <ul class="links-list list-unstyled">
          <li><a href="/produtos/categoria/vestidos">Vestidos</a></li>
          <li><a href="/produtos/categoria/sapatos">Sapatos</a></li>
          <li><a href="/produtos/categoria/mochilas">Mochilas</a></li>
          <li><a href="/produtos/categoria/olhos">Óculos</a></li>
          <li><a href="/produtos/categoria/braceletes">Relógios</a></li>
          <li><a href="/produtos/categoria/camisas">Camisas</a></li>
        </ul>
      </div>

      <div class="col-sm-12 col-lg-3">
        <h5>LINKS</h5>
        <ul class="links-list list-unstyled">
          <li><a href="{% url 'products:home' %}">Início</a></li>
          <li><a href="{% url 'products:products' %}">Loja</a></li>
          <li><a href="{% url 'page:about' %}">Sobre</a></li>
          <li><a href="{% url 'products:home' %}#featured-products">Destaques de Produtos</a></li>
          <li><a href="blog.html">Blog</a></li>
        </ul>
      </div>

      <div class="col-sm-12 col-lg-3">
        <h5>AJUDA</h5>
        <ul class="links-list list-unstyled">
          <li><a href="">Acompanhar Pedido</a></li>
          <li><a href="">Suporte</a></li>
          <li><a href="">FaQs</a></li>
        </ul>
      </div>
    </div>
    <hr>
    <p>@copyright Thunder Store</p>
  </div>
</footer>

templates/order_success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sucesso do pedido{% endblock title %}

{% block content %}
<main>
  <div class="success-page">
    <div>
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
      <h1>Sucesso</h1>
      <p>Seu pedido foi feito com sucesso.<br/>Enviaremos em breve!</p>
      <a href="{% url 'products:home' %}">Retornar</a>
    </div>
  </div>
</main>
{% endblock content %}

templates/pagination.html
<nav>
  <ul class="pagination">
		{% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">Anterior</a>
    </li>
    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}<a></li>
		{% endif %}
    <li class="page-item active">
      <a class="page-link" href="#"><span class="sr-only">{{ page.number }}</span></a>
    </li>
		{% if page.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">{{ page.next_page_number }}<a></li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Próximo</a>
    </li>
		{% endif %}
  </ul>
</nav>

templates/search_results.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Resultado de Busca{% endblock %}

{% block content %}
<main>
  {% if products %}
  <div class="top-banner">
    <h2>Resultados</h2>
  </div>

  <div class="container my-5">
    <div class="row">
      <div class="col-4 col-md-3">
        <ul class="list-group mb-3 mb-lg-0">
          <a class="text-decoration-none list-group-item list-group-item-light" href="{% url 'products:products' %}">
            Todos os produtos
          </a>

          {% for category in categories %}
          <a class="text-decoration-none list-group-item list-group-item-light" href="{% url 'products:filter_products' category.slug %}">{{ category.name }}</a>
          {% endfor %}
        </ul>
      </div>

      <div class="col-8 col-md-9">
        <div class="row">
          {% for merchandise in products %}
          <div class="col-sm-12 col-md-6 col-lg-4 mb-4">
            <div class="card h-100">
              <a href="{% url 'products:product_detail' merchandise.slug %}">
                <img class="card-img-top" src="{{ merchandise.image.url }}" alt="">
              </a>

              <div class="card-body d-flex flex-column justify-content-between">
                <a class="text-decoration-none text-dark" href="{% url 'products:product_detail' merchandise.slug %}">
                  <h5 class="card-title">{{ merchandise.name }}</h5>
                </a>
                <a class="text-decoration-none text-dark" href="{% url 'products:product_detail' merchandise.slug %}">
                  <p class="card-text font-weight-bold">{{ merchandise.price }}</p>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}

          {% if is_paginated %}
            {% include 'pagination.html' with page=page_obj %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  {% else %}
  <div class="top-banner">
    <h2>Nenhum Resultado</h2>
  </div>
  {% endif %}
</main>

{% include 'footer.html' %}
{% endblock content %}

templates/sign-up.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cadastrar{% endblock %}

{% block content %}

<main>
  <div id="login" class="container">
    <form action="">
      <h3>Cadastrar com</h3>
      <ul>
        <li><a><i class="bi bi-facebook"> Facebook</i></a></li>
        <li><a><i class="bi bi-google"> Google</i></a></li>
      </ul>
      <input type="text" class="form-control" placeholder="Name">
      <input type="text" class="form-control" placeholder="Email">
      <input type="text" class="form-control" placeholder="Senha">
      <input type="submit" class="form-control btn-black" value="Entrar">
      <p>Não tem uma conta?<a> Entrar</a><p>
    </form>
  </div>
</main>

{% include 'footer.html' %}
{% endblock content %}

templates/store.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Produtos{% endblock %}

{% block content %}
<main>
  <div class="top-banner">
    <h2>Loja</h2>
  </div>

  <div class="container my-5">
    <div class="row">
      <div class="col-4 col-md-3 col-lg-2">
        <ul class="list-group mb-3 mb-lg-0">
          <a class="text-decoration-none list-group-item list-group-item-light" href="{% url 'products:products' %}">
            Todos os produtos
          </a>

          {% for category in categories %}
          <a class="text-decoration-none list-group-item list-group-item-light" href="{% url 'products:filter_products' category.slug %}">{{ category.name }}</a>
          {% endfor %}
        </ul>
      </div>

      <div class="col-8 col-md-9 col-lg-10">
        <div class="row">
          {% for merchandise in products %}
          <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 mb-4">
            <div class="card h-100">
              <a href="{% url 'products:product_detail' merchandise.slug %}">
                <img class="card-img-top" src="{{ merchandise.image.url }}" alt="">
              </a>

              <div class="card-body d-flex flex-column justify-content-between">
                <a class="text-decoration-none text-dark" href="{% url 'products:product_detail' merchandise.slug %}">
                  <h5 class="card-title">{{ merchandise.name }}</h5>
                </a>
                <a class="text-decoration-none text-dark" href="{% url 'products:product_detail' merchandise.slug %}">
                  <p class="card-text font-weight-bold">{{ merchandise.price }}</p>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}

          {% if is_paginated %}
            {% include 'pagination.html' with page=page_obj %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>

{% include 'footer.html' %}
{% endblock content %}